### ISSUE TITLE
Feature search districts by city name

### ISSUE THREAD

**Issue by KinoThe-Kafkaesque** [Ysn4Irix/madina#10]
Hi i made use of this repo in school project a while and i noticed that  it would be nice if we can search for districts by city name and not only by city id . In addition this project would benefit better from something like meilisearch instead of mysql since most of its data is readonly . Thx for the awesome project.

**Comment by Ysn4Irix** [comment]
hi, thanks for your opinion and sorry for this late answer i will add searching by city name soon, if u have any ideo feel free to open an issue or dm me thank for using our Api
